
// Login and Routing
export const CHANGE_LOGGEDIN = 'CHANGE_LOGGEDIN';

// Profile Management
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const REQUEST_LOAD_PROFILE_PENDING = 'REQUEST_LOAD_PROFILE_PENDING';
export const REQUEST_LOAD_PROFILE_SUCCESS = 'REQUEST_LOAD_PROFILE_SUCCESS';
export const REQUEST_LOAD_PROFILE_FAILED = 'REQUEST_LOAD_PROFILE_FAILED';

export const REQUEST_REGISTER_PROFILE_PENDING = 'REQUEST_REGISTER_PROFILE_PENDING';
export const REQUEST_REGISTER_PROFILE_SUCCESS = 'REQUEST_REGISTER_PROFILE_SUCCESS';
export const REQUEST_REGISTER_PROFILE_FAILED = 'REQUEST_REGISTER_PROFILE_FAILED';

export const REQUEST_EDIT_PROFILE_PENDING = 'REQUEST_EDIT_PROFILE_PENDING';
export const REQUEST_EDIT_PROFILE_SUCCESS = 'REQUEST_EDIT_PROFILE_SUCCESS';
export const REQUEST_EDIT_PROFILE_FAILED = 'REQUEST_EDIT_PROFILE_FAILED';

